#local dev env only
services:
  mongodb:
    image: mongo:latest
    container_name: database
    env_file:
      - .env
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGODB_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGODB_INITDB_ROOT_PASSWORD}
    ports:
      - ${MONGODB_INITDB_PORT}:${MONGODB_INITDB_PORT}
    volumes:
      - ./.database:/data/db
